# Generated by Django 5.0.6 on 2024-05-30 05:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simp_dungeon', '0002_category_subscribers_categorysubscribe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='categories', through='simp_dungeon.CategorySubscribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
