# Generated by Django 5.0.6 on 2024-07-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simp_dungeon', '0002_categorysubscribe_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Title_en_us',
            field=models.CharField(max_length=125, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Title_ru',
            field=models.CharField(max_length=125, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_en_us',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_ru',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
